"""rename department

Revision ID: 20e4bab54793
Revises: ff9d22490080
Create Date: 2024-06-01 11:50:01.111231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e4bab54793'
down_revision = 'ff9d22490080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
   
    # ### end Alembic commands ###
